spring:
  application:
    name: SpringBoot-JPA
  config:
    import: "env/config-${spring.profiles.active}.properties"
  datasource:
    driver-class-name: ${DB_CLASSNAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: ${DB_TYPE}
    database-platform: ${DB_DIALECT}
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
logging:
  level:
    com.imadiaos.*: DEBUG
